### ISSUE TITLE
Normalization by the constant eigenvector

### ISSUE THREAD

**Issue by rflperry** [satra/mapalign#17]
In [line 141](https://github.com/satra/mapalign/blob/master/mapalign/embed.py#L141) of `embed.py`, in `_step_5` the eigenvectors are normalized by the 1st eigenvector `psi = vectors/vectors[:, [0]]`.

What is the purpose of this? I understand that the 1st eigenvector should be constant and so this ideally will amount to scaling and sign flips, but due to numerical issues it isn't going to be a constant vectors.

**Comment by satra** [comment]
you are correct on both fronts. it is to normalize and yes the normalization will have some numerical precision error due to floating point divisions. it cannot be used to address sign flips though. the flips are vector specific so cannot be determined a priori. it will flip signs depending on the constant vector. 

i believe this was put in just to force the 1st eigenvector to be a **1** vector.
